from SequinceCounter import generate_k_seqs, SequinceCounter, load_Sentences_names
from test_Parser import *


def process_json_data(inout_data: str) -> tempfile:
    # Parse the input JSON string into a Python dictionary
    data = json.loads(inout_data)
    # Convert the dictionary back to a JSON string with pretty formatting
    json_output = json.dumps(data, indent=4)
    # Create a temporary file to store the JSON data
    with tempfile.NamedTemporaryFile(delete=False, mode='w', newline='', suffix='.json') as tmp_file:
        tmp_file.write(json_output)  # Write the JSON data to the temporary file
    return tmp_file.name  # Return the path to the temporary file


def test_generate_k_seqs():
    """
    Test the generate_k_seqs work as needed and generate k word tuples with count
    """
    text = [["hello", "world"], ["hello", "world"]]
    assert generate_k_seqs(text, 2) == {'1_seq': [(('hello',), 2), (('world',), 2)], '2_seq': [(('hello', 'world'), 2)]}
    assert generate_k_seqs(text, 3) == {'1_seq': [(('hello',), 2), (('world',), 2)], '2_seq': [(('hello', 'world'), 2)],
                                        '3_seq': []}
    assert generate_k_seqs(text, 4) == {'1_seq': [(('hello',), 2), (('world',), 2)], '2_seq': [(('hello', 'world'), 2)],
                                        '3_seq': [], '4_seq': []}


json1 = process_json_data(data_str)
json2 = process_json_data(data_str2)
json3 = process_json_data(data_str3)
json4 = process_json_data(data_str4)
json5 = process_json_data(data_str5)
json6 = process_json_data(data_str6)


def test_load_sentence_names():
    """
    Test the load_sentence_names work as needed and get the sentence and names
    """
    loaded_data1 = load_Sentences_names(json1)
    assert loaded_data1 == (sentence1, name_res1)
    loaded_data2 = load_Sentences_names(json2)
    assert loaded_data2 == (sentence2, name_res2)
    loaded_data3 = load_Sentences_names(json3)
    assert loaded_data3 == (sentence3, name_res3)
    loaded_data4 = load_Sentences_names(json4)
    assert loaded_data4 == (sentence4, name_res4)
    loaded_data5 = load_Sentences_names(json5)
    assert loaded_data5 == (sentence5, name_res5)
    loaded_data6 = load_Sentences_names(json6)
    assert loaded_data6 == (sentence6, name_res6)


def test_equal_Csr():
    """
    Test the equal_Csr that the given json file is equal to the csv files
    """
    assert SequinceCounter(2, json_input_path=json1, preprocessed=True, N=2).return_results() == SequinceCounter(2,
                                                                                                                 sentence_input_path=csv_sentence1,
                                                                                                                 remove_input_path=csv_remved2,
                                                                                                                 N=2).return_results()
    assert SequinceCounter(2, json_input_path=json2, preprocessed=True, N=4).return_results() == SequinceCounter(2,
                                                                                                                 sentence_input_path=csv_sentence6,
                                                                                                                 remove_input_path=csv_remved1,
                                                                                                                 N=4).return_results()
    assert SequinceCounter(2, json_input_path=json3, preprocessed=True, N=5).return_results() == SequinceCounter(2,
                                                                                                                 sentence_input_path=csv_sentence2,
                                                                                                                 remove_input_path=csv_remved1,
                                                                                                                 N=5).return_results()
    assert SequinceCounter(2, json_input_path=json4, preprocessed=True, N=3).return_results() == SequinceCounter(2,
                                                                                                                 sentence_input_path=csv_sentence3,
                                                                                                                 remove_input_path=csv_remved1,
                                                                                                                 N=3).return_results()
    assert SequinceCounter(2, json_input_path=json5, preprocessed=True, N=6).return_results() == SequinceCounter(2,
                                                                                                                 sentence_input_path=csv_sentence4,
                                                                                                                 remove_input_path=csv_remved1,
                                                                                                                 N=6).return_results()
    assert SequinceCounter(2, json_input_path=json6, preprocessed=True, N=1).return_results() == SequinceCounter(2,
                                                                                                                 sentence_input_path=csv_sentence5,
                                                                                                                 remove_input_path=csv_remved1,
                                                                                                                 N=1).return_results()


empty_file = ('{\n'
              '    "Question 1": {\n'
              '        "Processed Sentences": [],\n'
              '        "Processed Names": []\n'
              '    }\n'
              '}')
empty_file_sen = create_temp_csv([], ["sentence"])
empty_file_json = process_json_data(empty_file)


def test_empty_files():
    """
    Test that empty dont make errors when supplied
    """
    res1 = ('{\n'
            '    "Question 2": {\n'
            '        "3-Seq Counts": [\n'
            '            [\n'
            '                "1_seq",\n'
            '                []\n'
            '            ],\n'
            '            [\n'
            '                "2_seq",\n'
            '                []\n'
            '            ],\n'
            '            [\n'
            '                "3_seq",\n'
            '                []\n'
            '            ]\n'
            '        ]\n'
            '    }\n'
            '}')
    res2 = ('{\n'
            '    "Question 2": {\n'
            '        "4-Seq Counts": [\n'
            '            [\n'
            '                "1_seq",\n'
            '                []\n'
            '            ],\n'
            '            [\n'
            '                "2_seq",\n'
            '                []\n'
            '            ],\n'
            '            [\n'
            '                "3_seq",\n'
            '                []\n'
            '            ],\n'
            '            [\n'
            '                "4_seq",\n'
            '                []\n'
            '            ]\n'
            '        ]\n'
            '    }\n'
            '}')
    assert SequinceCounter(2, json_input_path=empty_file_json, preprocessed=True, N=3).return_results() == res1
    assert SequinceCounter(2, sentence_input_path=empty_file_sen, remove_input_path=csv_remved1,
                           N=3).return_results() == res1
    assert SequinceCounter(2, json_input_path=empty_file_json, preprocessed=True, N=4).return_results() == res2
    assert SequinceCounter(2, sentence_input_path=empty_file_sen, remove_input_path=csv_remved1,
                           N=4).return_results() == res2


def test_k_seq():
    """
    tedt that k seq return the correct value and works as needed
    """
    result1 = ('{\n'
               '    "Question 2": {\n'
               '        "2-Seq Counts": [\n'
               '            [\n'
               '                "1_seq",\n'
               '                [\n'
               '                    [\n'
               '                        "chariot",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "harry",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "known",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "like",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "magician",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "platinum",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "red",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "rode",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "shined",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "silver",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "star",\n'
               '                        1\n'
               '                    ]\n'
               '                ]\n'
               '            ],\n'
               '            [\n'
               '                "2_seq",\n'
               '                [\n'
               '                    [\n'
               '                        "harry rode",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "known red",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "like star",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "red magician",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "rode silver",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "shined like",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "silver chariot",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "star platinum",\n'
               '                        1\n'
               '                    ]\n'
               '                ]\n'
               '            ]\n'
               '        ]\n'
               '    }\n'
               '}')
    result2 = ('{\n'
               '    "Question 2": {\n'
               '        "4-Seq Counts": [\n'
               '            [\n'
               '                "1_seq",\n'
               '                []\n'
               '            ],\n'
               '            [\n'
               '                "2_seq",\n'
               '                []\n'
               '            ],\n'
               '            [\n'
               '                "3_seq",\n'
               '                []\n'
               '            ],\n'
               '            [\n'
               '                "4_seq",\n'
               '                []\n'
               '            ]\n'
               '        ]\n'
               '    }\n'
               '}')
    result3 = ('{\n'
               '    "Question 2": {\n'
               '        "5-Seq Counts": [\n'
               '            [\n'
               '                "1_seq",\n'
               '                [\n'
               '                    [\n'
               '                        "about",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "and",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "black",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "bolt",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "boy",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "could",\n'
               '                        2\n'
               '                    ],\n'
               '                    [\n'
               '                        "couldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "curiously",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "cut",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "do",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore",\n'
               '                        4\n'
               '                    ],\n'
               '                    [\n'
               '                        "even",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forehead",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forever",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "hair",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "have",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "i",\n'
               '                        2\n'
               '                    ],\n'
               '                    [\n'
               '                        "if",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "is",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "jet",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "lightning",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "like",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "ll",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "mcgonagall",\n'
               '                        2\n'
               '                    ],\n'
               '                    [\n'
               '                        "professor",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "said",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "scar",\n'
               '                        2\n'
               '                    ],\n'
               '                    [\n'
               '                        "see",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "shaped",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "something",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "t",\n'
               '                        2\n'
               '                    ],\n'
               '                    [\n'
               '                        "that",\n'
               '                        2\n'
               '                    ],\n'
               '                    [\n'
               '                        "tuft",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "under",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "where",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "whispered",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "wouldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "yes",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "you",\n'
               '                        1\n'
               '                    ]\n'
               '                ]\n'
               '            ],\n'
               '            [\n'
               '                "2_seq",\n'
               '                [\n'
               '                    [\n'
               '                        "about scar",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "and mcgonagall",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "black hair",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "bolt lightning",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "boy forehead",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "could i",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "could see",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "couldn t",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "curiously shaped",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "cut like",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "do something",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore and",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore even",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore ll",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "even if",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forehead dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forever couldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "hair boy",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "have that",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "i could",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "i wouldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "if i",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "is that",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "jet black",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "like bolt",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "ll have",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "mcgonagall could",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "professor mcgonagall",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "said dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "scar dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "scar forever",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "see curiously",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "shaped cut",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "something about",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "t you",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "that scar",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "that where",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "tuft jet",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "under tuft",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "where whispered",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "whispered professor",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "wouldn t",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "yes said",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "you do",\n'
               '                        1\n'
               '                    ]\n'
               '                ]\n'
               '            ],\n'
               '            [\n'
               '                "3_seq",\n'
               '                [\n'
               '                    [\n'
               '                        "about scar dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "and mcgonagall could",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "black hair boy",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "boy forehead dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "could i wouldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "could see curiously",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "couldn t you",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "curiously shaped cut",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "cut like bolt",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "do something about",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore and mcgonagall",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore dumbledore ll",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore even if",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore ll have",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "even if i",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forehead dumbledore and",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forever couldn t",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "hair boy forehead",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "have that scar",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "i could i",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "i wouldn t",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "if i could",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "is that where",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "jet black hair",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "like bolt lightning",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "ll have that",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "mcgonagall could see",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "said dumbledore dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "scar dumbledore even",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "scar forever couldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "see curiously shaped",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "shaped cut like",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "something about scar",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "t you do",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "that scar forever",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "that where whispered",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "tuft jet black",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "under tuft jet",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "where whispered professor",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "whispered professor mcgonagall",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "yes said dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "you do something",\n'
               '                        1\n'
               '                    ]\n'
               '                ]\n'
               '            ],\n'
               '            [\n'
               '                "4_seq",\n'
               '                [\n'
               '                    [\n'
               '                        "about scar dumbledore even",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "and mcgonagall could see",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "black hair boy forehead",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "boy forehead dumbledore and",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "could i wouldn t",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "could see curiously shaped",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "couldn t you do",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "curiously shaped cut like",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "cut like bolt lightning",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "do something about scar",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore and mcgonagall could",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore dumbledore ll have",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore even if i",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore ll have that",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "even if i could",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forehead dumbledore and mcgonagall",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forever couldn t you",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "hair boy forehead dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "have that scar forever",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "i could i wouldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "if i could i",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "is that where whispered",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "jet black hair boy",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "ll have that scar",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "mcgonagall could see curiously",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "said dumbledore dumbledore ll",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "scar dumbledore even if",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "scar forever couldn t",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "see curiously shaped cut",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "shaped cut like bolt",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "something about scar dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "t you do something",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "that scar forever couldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "that where whispered professor",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "tuft jet black hair",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "under tuft jet black",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "where whispered professor mcgonagall",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "yes said dumbledore dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "you do something about",\n'
               '                        1\n'
               '                    ]\n'
               '                ]\n'
               '            ],\n'
               '            [\n'
               '                "5_seq",\n'
               '                [\n'
               '                    [\n'
               '                        "about scar dumbledore even if",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "and mcgonagall could see curiously",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "black hair boy forehead dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "boy forehead dumbledore and mcgonagall",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "could see curiously shaped cut",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "couldn t you do something",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "curiously shaped cut like bolt",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "do something about scar dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore and mcgonagall could see",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore dumbledore ll have that",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore even if i could",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore ll have that scar",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "even if i could i",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forehead dumbledore and mcgonagall could",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forever couldn t you do",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "hair boy forehead dumbledore and",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "have that scar forever couldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "i could i wouldn t",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "if i could i wouldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "is that where whispered professor",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "jet black hair boy forehead",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "ll have that scar forever",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "mcgonagall could see curiously shaped",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "said dumbledore dumbledore ll have",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "scar dumbledore even if i",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "scar forever couldn t you",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "see curiously shaped cut like",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "shaped cut like bolt lightning",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "something about scar dumbledore even",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "t you do something about",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "that scar forever couldn t",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "that where whispered professor mcgonagall",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "tuft jet black hair boy",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "under tuft jet black hair",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "yes said dumbledore dumbledore ll",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "you do something about scar",\n'
               '                        1\n'
               '                    ]\n'
               '                ]\n'
               '            ]\n'
               '        ]\n'
               '    }\n'
               '}')
    result4 = ('{\n'
               '    "Question 2": {\n'
               '        "3-Seq Counts": [\n'
               '            [\n'
               '                "1_seq",\n'
               '                [\n'
               '                    [\n'
               '                        "about",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "and",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "black",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "bolt",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "boy",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "could",\n'
               '                        2\n'
               '                    ],\n'
               '                    [\n'
               '                        "couldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "curiously",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "cut",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "do",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore",\n'
               '                        4\n'
               '                    ],\n'
               '                    [\n'
               '                        "even",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forehead",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forever",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "hair",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "have",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "i",\n'
               '                        2\n'
               '                    ],\n'
               '                    [\n'
               '                        "if",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "is",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "jet",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "lightning",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "like",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "ll",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "mcgonagall",\n'
               '                        2\n'
               '                    ],\n'
               '                    [\n'
               '                        "professor",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "said",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "scar",\n'
               '                        2\n'
               '                    ],\n'
               '                    [\n'
               '                        "see",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "shaped",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "something",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "t",\n'
               '                        2\n'
               '                    ],\n'
               '                    [\n'
               '                        "that",\n'
               '                        2\n'
               '                    ],\n'
               '                    [\n'
               '                        "tuft",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "under",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "where",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "whispered",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "wouldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "yes",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "you",\n'
               '                        1\n'
               '                    ]\n'
               '                ]\n'
               '            ],\n'
               '            [\n'
               '                "2_seq",\n'
               '                [\n'
               '                    [\n'
               '                        "about scar",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "and mcgonagall",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "black hair",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "bolt lightning",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "boy forehead",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "could i",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "could see",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "couldn t",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "curiously shaped",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "cut like",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "do something",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore and",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore even",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore ll",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "even if",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forehead dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forever couldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "hair boy",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "have that",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "i could",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "i wouldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "if i",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "is that",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "jet black",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "like bolt",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "ll have",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "mcgonagall could",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "professor mcgonagall",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "said dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "scar dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "scar forever",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "see curiously",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "shaped cut",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "something about",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "t you",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "that scar",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "that where",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "tuft jet",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "under tuft",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "where whispered",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "whispered professor",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "wouldn t",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "yes said",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "you do",\n'
               '                        1\n'
               '                    ]\n'
               '                ]\n'
               '            ],\n'
               '            [\n'
               '                "3_seq",\n'
               '                [\n'
               '                    [\n'
               '                        "about scar dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "and mcgonagall could",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "black hair boy",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "boy forehead dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "could i wouldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "could see curiously",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "couldn t you",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "curiously shaped cut",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "cut like bolt",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "do something about",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore and mcgonagall",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore dumbledore ll",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore even if",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "dumbledore ll have",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "even if i",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forehead dumbledore and",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "forever couldn t",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "hair boy forehead",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "have that scar",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "i could i",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "i wouldn t",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "if i could",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "is that where",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "jet black hair",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "like bolt lightning",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "ll have that",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "mcgonagall could see",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "said dumbledore dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "scar dumbledore even",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "scar forever couldn",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "see curiously shaped",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "shaped cut like",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "something about scar",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "t you do",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "that scar forever",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "that where whispered",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "tuft jet black",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "under tuft jet",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "where whispered professor",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "whispered professor mcgonagall",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "yes said dumbledore",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "you do something",\n'
               '                        1\n'
               '                    ]\n'
               '                ]\n'
               '            ]\n'
               '        ]\n'
               '    }\n'
               '}')
    result5 = ('{\n'
               '    "Question 2": {\n'
               '        "4-Seq Counts": [\n'
               '            [\n'
               '                "1_seq",\n'
               '                [\n'
               '                    [\n'
               '                        "called",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "his",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "marry",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "max",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "name",\n'
               '                        1\n'
               '                    ]\n'
               '                ]\n'
               '            ],\n'
               '            [\n'
               '                "2_seq",\n'
               '                [\n'
               '                    [\n'
               '                        "called his",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "his name",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "marry called",\n'
               '                        1\n'
               '                    ]\n'
               '                ]\n'
               '            ],\n'
               '            [\n'
               '                "3_seq",\n'
               '                [\n'
               '                    [\n'
               '                        "called his name",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "marry called his",\n'
               '                        1\n'
               '                    ]\n'
               '                ]\n'
               '            ],\n'
               '            [\n'
               '                "4_seq",\n'
               '                [\n'
               '                    [\n'
               '                        "marry called his name",\n'
               '                        1\n'
               '                    ]\n'
               '                ]\n'
               '            ]\n'
               '        ]\n'
               '    }\n'
               '}')
    result6 = ('{\n'
               '    "Question 2": {\n'
               '        "1-Seq Counts": [\n'
               '            [\n'
               '                "1_seq",\n'
               '                [\n'
               '                    [\n'
               '                        "called",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "his",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "marry",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "max",\n'
               '                        1\n'
               '                    ],\n'
               '                    [\n'
               '                        "name",\n'
               '                        1\n'
               '                    ]\n'
               '                ]\n'
               '            ]\n'
               '        ]\n'
               '    }\n'
               '}')
    assert SequinceCounter(2, json_input_path=json1, preprocessed=True, N=2).return_results() == result1
    assert SequinceCounter(2, sentence_input_path=csv_sentence6, remove_input_path=csv_remved1,
                           N=4).return_results() == result2
    assert SequinceCounter(2, json_input_path=json3, preprocessed=True, N=5).return_results() == result3
    assert SequinceCounter(2, sentence_input_path=csv_sentence3, remove_input_path=csv_remved1,
                           N=3).return_results() == result4
    assert SequinceCounter(2, json_input_path=json5, preprocessed=True, N=4).return_results() == result5
    assert SequinceCounter(2, sentence_input_path=csv_sentence5, remove_input_path=csv_remved1,
                           N=1).return_results() == result6
